const LABIAL = "labial"
const BILAB = "bilabial"
const LAB_DEN = "labiodental"
const CORONAL = "coronal"
const INTER_DENT = "interdental"
const DENTAL = "dental"
const ALV = "alveolar"
const PAL_ALV = "palatoalveolar"
const RETROFLEX = "retroflex"
const DORSAL = "dorsal"
const PAL = "palatal"
const VEL = "velar"
const UVU = "uvular"
const PHAR = "pharyngeal"
const LARYN = "laryngeal"
const EPIG = "epiglottal"
const GLOTTAL = "glottal"

export const place = {
    LABIAL,
    BILAB,
    LAB_DEN,
    CORONAL,
    INTER_DENT,
    DENTAL,
    ALV,
    PAL_ALV,
    RETROFLEX,
    DORSAL,
    PAL,
    VEL,
    UVU,
    PHAR,
    LARYN,
    EPIG,
    GLOTTAL,
}

export function is_dental(place) {
    return (
        place === LABIAL ||
        place === BILAB ||
        place === LAB_DEN
    )
}

export function is_coronal(place) {
    return (
        place === CORONAL ||
        place === INTER_DENT ||
        place === DENTAL ||
        place === ALV ||
        place === PAL_ALV ||
        place === RETROFLEX
    )
}

export function is_dorsal(place) {
    return (
        place === DORSAL ||
        place === PAL ||
        place === VEL ||
        place === UVU
    )
}

export function is_laryngeal(place) {
    return (
        place === LARYN ||
        place === EPIG ||
        place === GLOTTAL
    )
}

const STOP = "stop"
const NASAL = "nasal"
const FRIC = "fricative"
const LAT_FRIC = "lateral fricative"
const AFF = "affricate"
const TRIL = "trill"
const TAP = "tap"
const APPROX = "approximant"
const LAT = "lateral"
const LAT_AFF = "lateral affricate"

export const manner = {
    STOP,
    NASAL,
    FRIC,
    LAT_FRIC,
    AFF,
    TRIL,
    TAP,
    APPROX,
    LAT
}

const SYL = "syllabic"
const STRES = "stress"
const LONG = "long"
const CONS = "consonantal"
const SON = "sonorant"
const CONT = "continuant"
const DELREL = "delayed release"
const VOICE = "voice"
const SP_GLOT = "spread glottis"
const CON_GLOT = "constricted glottis"
const ROUND = "round"
const ANT = "anterior"
const DISTRO = "distributed"
const STRID = "strident"
const HIGH = "high"
const LOW = "low"
const FRONT = "front"
const BACK = "back"
const TENSE = "tense"

export const features = {
    SYL,
    STRES,
    LONG,
    CONS,
    SON,
    CONT,
    DELREL,
    APPROX,
    TAP,
    TRIL,
    LAT,
    NASAL,
    VOICE,
    SP_GLOT,
    CON_GLOT,
    LABIAL,
    ROUND,
    LAB_DEN,
    CORONAL,
    ANT,
    DISTRO,
    STRID,
    DORSAL,
    HIGH,
    LOW,
    FRONT,
    BACK,
    TENSE,
}

function pair_nums(...nums) {
    let str = ""
    for (let num of nums) {
        str += String(num)
    }
    return parseInt(str, 10)
}

export default [
    {
        name: "glottal stop",
        place: GLOTTAL,
        manner: STOP,
        consonant: true,
        vowel: false,
        ipa_sym: "ʔ",
        ipa_ent: "&#660;",
        branner: "?",
        number: 113,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: -1,
            DELREL: -1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: -1,
            SP_GLOT: -1,
            CON_GLOT: +1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "high front tense unrounded vowel",
        place: DORSAL,
        consonant: false,
        vowel: true,
        ipa_sym: "i",
        ipa_ent: "&#105;",
        branner: "i",
        number: 301,
        features: {
            SYL: +1,
            STRES: -1,
            LONG: -1,
            CONS: -1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: +1,
            LOW: -1,
            FRONT: +1,
            BACK: -1,
            TENSE: +1,
        }
    },
    {
        name: "high front tense rounded vowel",
        place: DORSAL,
        consonant: false,
        vowel: true,
        ipa_sym: "y",
        ipa_ent: "&#121;",
        branner: "y",
        number: 309,
        features: {
            SYL: +1,
            STRES: -1,
            LONG: -1,
            CONS: -1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: +1,
            ROUND: +1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: +1,
            LOW: -1,
            FRONT: +1,
            BACK: -1,
            TENSE: +1,
        }
    },
    {
        name: "near-high front lax unrounded vowel",
        place: DORSAL,
        consonant: false,
        vowel: true,
        ipa_sym: "ɪ",
        ipa_ent: "&#618;",
        branner: "I",
        number: 319,
        features: {
            SYL: +1,
            STRES: -1,
            LONG: -1,
            CONS: -1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: +1,
            LOW: -1,
            FRONT: +1,
            BACK: -1,
            TENSE: -1,
        }
    },
    {
        name: "near-high front lax rounded vowel",
        place: DORSAL,
        consonant: false,
        vowel: true,
        ipa_sym: "ʏ",
        ipa_ent: "&#655;",
        branner: "Y",
        number: 320,
        features: {
            SYL: +1,
            STRES: -1,
            LONG: -1,
            CONS: -1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: +1,
            ROUND: +1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: +1,
            LOW: -1,
            FRONT: +1,
            BACK: -1,
            TENSE: -1,
        }
    },
    {
        name: "high-mid front tense unrounded vowel",
        place: DORSAL,
        consonant: false,
        vowel: true,
        ipa_sym: "e",
        ipa_ent: "&#101;",
        branner: "e",
        number: 302,
        features: {
            SYL: +1,
            STRES: -1,
            LONG: -1,
            CONS: -1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: -1,
            LOW: -1,
            FRONT: +1,
            BACK: -1,
            TENSE: +1,
        }
    },
    {
        name: "high-mid front tense rounded vowel",
        place: DORSAL,
        consonant: false,
        vowel: true,
        ipa_sym: "ø",
        ipa_ent: "&#248;",
        branner: "o/)",
        number: 310,
        features: {
            SYL: +1,
            STRES: -1,
            LONG: -1,
            CONS: -1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: +1,
            ROUND: +1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: -1,
            LOW: -1,
            FRONT: +1,
            BACK: -1,
            TENSE: +1,
        }
    },
    {
        name: "low-mid front unrounded vowel",
        place: DORSAL,
        consonant: false,
        vowel: true,
        ipa_sym: "ε",
        ipa_ent: "&#603;",
        branner: "E",
        number: 303,
        features: {
            SYL: +1,
            STRES: -1,
            LONG: -1,
            CONS: -1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: -1,
            LOW: -1,
            FRONT: +1,
            BACK: -1,
            TENSE: -1,
        }
    },
    {
        name: "low-mid front rounded vowel",
        place: DORSAL,
        consonant: false,
        vowel: true,
        ipa_sym: "œ",
        ipa_ent: "&#339;",
        branner: "oe)",
        number: 311,
        features: {
            SYL: +1,
            STRES: -1,
            LONG: -1,
            CONS: -1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: +1,
            ROUND: +1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: -1,
            LOW: -1,
            FRONT: +1,
            BACK: -1,
            TENSE: -1,
        }
    },
    {
        name: "near-low front unrounded vowel",
        place: DORSAL,
        consonant: false,
        vowel: true,
        ipa_sym: "æ",
        ipa_ent: "&#230;",
        branner: "ae)",
        number: 325,
        features: {
            SYL: +1,
            STRES: -1,
            LONG: -1,
            CONS: -1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: -1,
            LOW: +1,
            FRONT: +1,
            BACK: -1,
            TENSE: +1,
        }
    },
    {
        name: "low front unrounded vowel",
        place: DORSAL,
        consonant: false,
        vowel: true,
        ipa_sym: "a",
        ipa_ent: "&#97;",
        branner: "a",
        number: 304,
        features: {
            SYL: +1,
            STRES: -1,
            LONG: -1,
            CONS: -1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: -1,
            LOW: +1,
            FRONT: +1,
            BACK: -1,
            TENSE: 0,
        }
    },
    {
        name: "low front rounded vowel",
        place: DORSAL,
        consonant: false,
        vowel: true,
        ipa_sym: "Œ",
        ipa_ent: "&#630;",
        branner: "OE)",
        number: 312,
        features: {
            SYL: +1,
            STRES: -1,
            LONG: -1,
            CONS: -1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: +1,
            ROUND: +1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: -1,
            LOW: +1,
            FRONT: +1,
            BACK: -1,
            TENSE: 0,
        }
    },
    {
        name: "high central tense unrounded vowel",
        place: DORSAL,
        consonant: false,
        vowel: true,
        ipa_sym: "ɨ",
        ipa_ent: "&#616;",
        branner: "i-",
        number: 317,
        features: {
            SYL: +1,
            STRES: -1,
            LONG: -1,
            CONS: -1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: +1,
            LOW: -1,
            FRONT: -1,
            BACK: -1,
            TENSE: +1,
        }
    },
    {
        name: "high central tense rounded vowel",
        place: DORSAL,
        consonant: false,
        vowel: true,
        ipa_sym: "ʉ",
        ipa_ent: "&#649;",
        branner: "u-",
        number: 318,
        features: {
            SYL: +1,
            STRES: -1,
            LONG: -1,
            CONS: -1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: +1,
            ROUND: +1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: +1,
            LOW: -1,
            FRONT: -1,
            BACK: -1,
            TENSE: +1,
        }
    },
    {
        name: "schwa",
        place: DORSAL,
        consonant: false,
        vowel: true,
        ipa_sym: "ə",
        ipa_ent: "&#601;",
        branner: "@",
        number: 322,
        features: {
            SYL: +1,
            STRES: -1,
            LONG: -1,
            CONS: -1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: -1,
            LOW: -1,
            FRONT: -1,
            BACK: -1,
            TENSE: -1,
        }
    },
    {
        name: "high back tense unrounded vowel",
        place: DORSAL,
        consonant: false,
        vowel: true,
        ipa_sym: "ɯ",
        ipa_ent: "&#623;",
        branner: "m&",
        number: 316,
        features: {
            SYL: +1,
            STRES: -1,
            LONG: -1,
            CONS: -1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: +1,
            LOW: -1,
            FRONT: -1,
            BACK: +1,
            TENSE: +1,
        }
    },
    {
        name: "high back tense rounded vowel",
        place: DORSAL,
        consonant: false,
        vowel: true,
        ipa_sym: "u",
        ipa_ent: "&#117;",
        branner: "u",
        number: 308,
        features: {
            SYL: +1,
            STRES: -1,
            LONG: -1,
            CONS: -1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: +1,
            ROUND: +1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: +1,
            LOW: -1,
            FRONT: -1,
            BACK: +1,
            TENSE: +1,
        }
    },
    {
        name: "near-high back lax rounded vowel",
        place: DORSAL,
        consonant: false,
        vowel: true,
        ipa_sym: "ʊ",
        ipa_ent: "&#650;",
        branner: "U",
        number: 321,
        features: {
            SYL: +1,
            STRES: -1,
            LONG: -1,
            CONS: -1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: +1,
            ROUND: +1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: +1,
            LOW: -1,
            FRONT: -1,
            BACK: +1,
            TENSE: -1,
        }
    },
    {
        name: "high-mid back tense unrounded vowel",
        place: DORSAL,
        consonant: false,
        vowel: true,
        ipa_sym: "ɤ",
        ipa_ent: "&#612;",
        branner: `U"`,
        number: 315,
        features: {
            SYL: +1,
            STRES: -1,
            LONG: -1,
            CONS: -1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: -1,
            LOW: -1,
            FRONT: -1,
            BACK: +1,
            TENSE: +1,
        }
    },
    {
        name: "high-mid back tense rounded vowel",
        place: DORSAL,
        consonant: false,
        vowel: true,
        ipa_sym: "o",
        ipa_ent: "&#111;",
        branner: "o",
        number: 307,
        features: {
            SYL: +1,
            STRES: -1,
            LONG: -1,
            CONS: -1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: +1,
            ROUND: +1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: -1,
            LOW: -1,
            FRONT: -1,
            BACK: +1,
            TENSE: +1,
        }
    },
    {
        name: "low-mid back lax unrounded vowel",
        place: DORSAL,
        consonant: false,
        vowel: true,
        ipa_sym: "ʌ",
        ipa_ent: "&#652;",
        branner: "v&",
        number: 314,
        features: {
            SYL: +1,
            STRES: -1,
            LONG: -1,
            CONS: -1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: -1,
            LOW: -1,
            FRONT: -1,
            BACK: +1,
            TENSE: -1,
        }
    },
    {
        name: "low-mid back lax rounded vowel",
        place: DORSAL,
        consonant: false,
        vowel: true,
        ipa_sym: "ɔ",
        ipa_ent: "&#596;",
        branner: "c&",
        number: 306,
        features: {
            SYL: +1,
            STRES: -1,
            LONG: -1,
            CONS: -1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: +1,
            ROUND: +1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: -1,
            LOW: -1,
            FRONT: -1,
            BACK: +1,
            TENSE: -1,
        }
    },
    {
        name: "low back unrounded vowel",
        place: DORSAL,
        consonant: false,
        vowel: true,
        ipa_sym: "ɑ",
        ipa_ent: "&#593;",
        branner: `a"`,
        number: 305,
        features: {
            SYL: +1,
            STRES: -1,
            LONG: -1,
            CONS: -1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: -1,
            LOW: +1,
            FRONT: -1,
            BACK: +1,
            TENSE: 0,
        }
    },
    {
        name: "low back rounded vowel",
        place: DORSAL,
        consonant: false,
        vowel: true,
        ipa_sym: "ɒ",
        ipa_ent: "&#594;",
        branner: `a"&`,
        number: 313,
        features: {
            SYL: +1,
            STRES: -1,
            LONG: -1,
            CONS: -1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: +1,
            ROUND: +1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: -1,
            LOW: +1,
            FRONT: -1,
            BACK: +1,
            TENSE: 0,
        }
    },
    {
        name: "voiceless bilabial stop",
        place: BILAB,
        manner: STOP,
        consonant: true,
        vowel: false,
        ipa_sym: "p",
        ipa_ent: "&#112;",
        branner: "p",
        number: 101,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: -1,
            DELREL: -1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: -1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: +1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiced bilabial stop",
        place: BILAB,
        manner: STOP,
        consonant: true,
        vowel: false,
        ipa_sym: "b",
        ipa_ent: "&#98;",
        branner: "b",
        number: 102,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: -1,
            DELREL: -1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: +1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiced bilabial nasal",
        place: BILAB,
        manner: NASAL,
        consonant: true,
        vowel: false,
        ipa_sym: "m",
        ipa_ent: "&#109;",
        branner: "m",
        number: 114,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: +1,
            CONT: -1,
            DELREL: 0,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: +1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: +1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiceless bilabial nasal",
        place: BILAB,
        manner: NASAL,
        consonant: true,
        vowel: false,
        ipa_sym: "m̥",
        ipa_ent: "&#109;&#805;",
        branner: "mV)",
        number: pair_nums(114, 402),
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: +1,
            CONT: -1,
            DELREL: 0,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: +1,
            VOICE: -1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: +1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiceless bilabial fricative",
        place: BILAB,
        manner: FRIC,
        consonant: true,
        vowel: false,
        ipa_sym: "ɸ",
        ipa_ent: "&#632;",
        branner: `P"`,
        number: 126,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: +1,
            DELREL: +1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: -1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: +1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiced bilabial fricative",
        place: BILAB,
        manner: FRIC,
        consonant: true,
        vowel: false,
        ipa_sym: "β",
        ipa_ent: "&#946;",
        branner: `B"`,
        number: 127,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: +1,
            DELREL: +1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: +1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiced bilabial trill",
        place: BILAB,
        manner: TRIL,
        consonant: true,
        vowel: false,
        ipa_sym: "ʙ",
        ipa_ent: "&#665;",
        branner: "B",
        number: 121,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: +1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: +1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiceless bilabial trill",
        place: BILAB,
        manner: TRIL,
        consonant: true,
        vowel: false,
        ipa_sym: "ʙ̥",
        ipa_ent: "&#665;&#805;",
        branner: "BV)",
        number: pair_nums(121, 402),
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: +1,
            LAT: -1,
            NASAL: -1,
            VOICE: -1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: +1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiceless labiodental affricate",
        place: LAB_DEN,
        manner: AFF,
        consonant: true,
        vowel: false,
        ipa_sym: "p̪͡f",
        ipa_ent: "&#112;&#810;&#865;&#102;",
        branner: "p[f))",
        number: pair_nums(101, 408, 128),
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: -1,
            DELREL: +1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: -1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: +1,
            ROUND: -1,
            LAB_DEN: +1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiced labiodental affricate",
        place: LAB_DEN,
        manner: AFF,
        consonant: true,
        vowel: false,
        ipa_sym: "b̪͡v",
        ipa_ent: "&#98;&#810;&#865;&#118;",
        branner: "b[v))",
        number: pair_nums(102, 408, 129),
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: -1,
            DELREL: +1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: +1,
            ROUND: -1,
            LAB_DEN: +1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiced labiodental nasal",
        place: LAB_DEN,
        manner: NASAL,
        consonant: true,
        vowel: false,
        ipa_sym: "ɱ",
        ipa_ent: "&#625;",
        branner: `m"`,
        number: 115,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: +1,
            CONT: -1,
            DELREL: 0,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: +1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: +1,
            ROUND: -1,
            LAB_DEN: +1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiceless labiodental fricative",
        place: LAB_DEN,
        manner: FRIC,
        consonant: true,
        vowel: false,
        ipa_sym: "f",
        ipa_ent: "&#102;",
        branner: "f",
        number: 128,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: +1,
            DELREL: +1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: -1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: +1,
            ROUND: -1,
            LAB_DEN: +1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiced labiodental fricative",
        place: LAB_DEN,
        manner: FRIC,
        consonant: true,
        vowel: false,
        ipa_sym: "v",
        ipa_ent: "&#118;",
        branner: "v",
        number: 129,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: +1,
            DELREL: +1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: +1,
            ROUND: -1,
            LAB_DEN: +1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiced labiodental approximant",
        place: LAB_DEN,
        manner: APPROX,
        consonant: true,
        vowel: false,
        ipa_sym: "ʋ",
        ipa_ent: "&#651;",
        branner: `v"`,
        number: 150,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: +1,
            ROUND: -1,
            LAB_DEN: +1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiceless alveolar stop",
        place: ALV,
        manner: STOP,
        consonant: true,
        vowel: false,
        ipa_sym: "t",
        ipa_ent: "&#116;",
        branner: "t",
        number: 103,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: -1,
            DELREL: -1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: -1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: +1,
            ANT: +1,
            DISTRO: -1,
            STRID: -1,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiced alveolar stop",
        place: ALV,
        manner: STOP,
        consonant: true,
        vowel: false,
        ipa_sym: "d",
        ipa_ent: "&#100;",
        branner: "d",
        number: 104,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: -1,
            DELREL: -1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: +1,
            ANT: +1,
            DISTRO: -1,
            STRID: -1,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiceless dental stop",
        place: DENTAL,
        manner: STOP,
        consonant: true,
        vowel: false,
        ipa_sym: "t̪",
        ipa_ent: "&#116;&#810;",
        branner: "t[",
        number: pair_nums(103, 408),
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: -1,
            DELREL: -1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: -1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: +1,
            ANT: +1,
            DISTRO: +1,
            STRID: -1,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiced dental stop",
        place: DENTAL,
        manner: STOP,
        consonant: true,
        vowel: false,
        ipa_sym: "d̪",
        ipa_ent: "&#100;&#810;",
        branner: "d[",
        number: pair_nums(104, 408),
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: -1,
            DELREL: -1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: +1,
            ANT: +1,
            DISTRO: +1,
            STRID: -1,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiceless dental fricative",
        place: INTER_DENT,
        manner: FRIC,
        consonant: true,
        vowel: false,
        ipa_sym: "θ",
        ipa_ent: "&#952;",
        branner: "0-",
        number: 130,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: +1,
            DELREL: +1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: -1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: +1,
            ANT: +1,
            DISTRO: +1,
            STRID: -1,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiced dental fricative",
        place: INTER_DENT,
        manner: FRIC,
        consonant: true,
        vowel: false,
        ipa_sym: "ð",
        ipa_ent: "&#240;",
        branner: "d-",
        number: 131,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: +1,
            DELREL: +1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: +1,
            ANT: +1,
            DISTRO: +1,
            STRID: -1,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiced alveolar nasal",
        place: ALV,
        manner: NASAL,
        consonant: true,
        vowel: false,
        ipa_sym: "n",
        ipa_ent: "&#110;",
        branner: "n",
        number: 116,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: +1,
            CONT: -1,
            DELREL: 0,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: +1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: +1,
            ANT: +1,
            DISTRO: -1,
            STRID: -1,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiceless alveolar affricate",
        place: ALV,
        manner: AFF,
        consonant: true,
        vowel: false,
        ipa_sym: "t͡s",
        ipa_ent: "&#116;&#865;&#115;",
        branner: "ts))",
        number: pair_nums(103, 132),
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: -1,
            DELREL: +1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: -1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: +1,
            ANT: +1,
            DISTRO: -1,
            STRID: +1,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiced alveolar affricate",
        place: ALV,
        manner: AFF,
        consonant: true,
        vowel: false,
        ipa_sym: "d͡z",
        ipa_ent: "&#100;&#865;&#122;",
        branner: "dz))",
        number: pair_nums(104, 133),
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: -1,
            DELREL: +1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: +1,
            ANT: +1,
            DISTRO: -1,
            STRID: +1,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiceless alveolar fricative",
        place: ALV,
        manner: FRIC,
        consonant: true,
        vowel: false,
        ipa_sym: "s",
        ipa_ent: "&#115;",
        branner: "s",
        number: 132,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: +1,
            DELREL: +1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: -1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: +1,
            ANT: +1,
            DISTRO: -1,
            STRID: +1,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiced alveolar fricative",
        place: ALV,
        manner: FRIC,
        consonant: true,
        vowel: false,
        ipa_sym: "z",
        ipa_ent: "&#122;",
        branner: "z",
        number: 133,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: +1,
            DELREL: +1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: +1,
            ANT: +1,
            DISTRO: -1,
            STRID: +1,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiceless alveolar lateral affricate",
        place: ALV,
        manner: LAT_AFF,
        consonant: true,
        vowel: false,
        ipa_sym: "t͡ɬ",
        ipa_ent: "&#116;&#865;&#620;",
        branner: "tl-))",
        number: pair_nums(103, 148),
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: -1,
            DELREL: +1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: -1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: +1,
            ANT: +1,
            DISTRO: -1,
            STRID: +1,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiced alveolar lateral affricate",
        place: ALV,
        manner: LAT_AFF,
        consonant: true,
        vowel: false,
        ipa_sym: "d͡ɮ",
        ipa_ent: "&#100;&#865;&#622;",
        branner: `dl3")))`,
        number: pair_nums(104, 149),
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: -1,
            DELREL: +1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: +1,
            ANT: +1,
            DISTRO: -1,
            STRID: +1,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiceless alveolar lateral fricative",
        place: ALV,
        manner: LAT_FRIC,
        consonant: true,
        vowel: false,
        ipa_sym: "ɬ",
        ipa_ent: "&#620;",
        branner: "l-",
        number: 148,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: +1,
            DELREL: +1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: +1,
            NASAL: -1,
            VOICE: -1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: +1,
            ANT: +1,
            DISTRO: -1,
            STRID: -1,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiced alveolar lateral fricative",
        place: ALV,
        manner: LAT_FRIC,
        consonant: true,
        vowel: false,
        ipa_sym: "ɮ",
        ipa_ent: "&#622;",
        branner: `l3")`,
        number: 149,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: +1,
            DELREL: +1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: +1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: +1,
            ANT: +1,
            DISTRO: -1,
            STRID: -1,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiced alveolar approximant",
        place: ALV,
        manner: APPROX,
        consonant: true,
        vowel: false,
        ipa_sym: "ɹ",
        ipa_ent: "&#633;",
        branner: "r&",
        number: 151,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: +1,
            ANT: -1,
            DISTRO: +1,
            STRID: -1,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiced alveolar trill",
        place: ALV,
        manner: TRIL,
        consonant: true,
        vowel: false,
        ipa_sym: "r",
        ipa_ent: "&#114;",
        branner: "r",
        number: 122,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: +1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: +1,
            ANT: +1,
            DISTRO: -1,
            STRID: -1,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiced alveolar tap",
        place: ALV,
        manner: TAP,
        consonant: true,
        vowel: false,
        ipa_sym: "ɾ",
        ipa_ent: "&#638;",
        branner: `r"`,
        number: 124,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: +1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: +1,
            ANT: +1,
            DISTRO: -1,
            STRID: -1,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiced alveolar lateral",
        place: ALV,
        manner: LAT,
        consonant: true,
        vowel: false,
        ipa_sym: "l",
        ipa_ent: "&#108;",
        branner: "l",
        number: 155,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: -1,
            LAT: +1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: +1,
            ANT: +1,
            DISTRO: -1,
            STRID: -1,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "dark l",
        place: ALV,
        manner: LAT,
        consonant: true,
        vowel: false,
        ipa_sym: "ɫ",
        ipa_ent: "&#619;",
        branner: "l~)",
        number: 209,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: +1,
            CONT: +1,
            DELREL: 0,
            APPROX: +1,
            TAP: -1,
            TRIL: -1,
            LAT: +1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: +1,
            ANT: +1,
            DISTRO: -1,
            STRID: -1,
            DORSAL: +1,
            HIGH: +1,
            LOW: 0,
            FRONT: 0,
            BACK: +1,
            TENSE: 0
        }
    },
    {
        name: "voiceless palatoalveolar affricate",
        place: PAL_ALV,
        manner: AFF,
        consonant: true,
        vowel: false,
        ipa_sym: "t͡ʃ",
        ipa_ent: "&#116;&#865;&#643;",
        branner: "tS))",
        number: pair_nums(103, 134),
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: -1,
            DELREL: +1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: -1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: +1,
            ANT: -1,
            DISTRO: +1,
            STRID: +1,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiced palatoalveolar affricate",
        place: PAL_ALV,
        manner: AFF,
        consonant: true,
        vowel: false,
        ipa_sym: "d͡ʒ",
        ipa_ent: "&#100;&#865;&#658;",
        branner: `d3"))`,
        number: pair_nums(104, 135),
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: -1,
            DELREL: +1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: +1,
            ANT: -1,
            DISTRO: +1,
            STRID: +1,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiceless palatoalveolar fricative",
        place: PAL_ALV,
        manner: FRIC,
        consonant: true,
        vowel: false,
        ipa_sym: "ʃ",
        ipa_ent: "&#643;",
        branner: "S",
        number: 134,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: +1,
            DELREL: +1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: -1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: +1,
            ANT: -1,
            DISTRO: +1,
            STRID: +1,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiced palatoalveolar fricative",
        place: PAL_ALV,
        manner: FRIC,
        consonant: true,
        vowel: false,
        ipa_sym: "ʒ",
        ipa_ent: "&#658;",
        branner: `3"`,
        number: 135,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: +1,
            DELREL: +1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: +1,
            ANT: -1,
            DISTRO: +1,
            STRID: +1,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiceless velar stop",
        place: VEL,
        manner: STOP,
        consonant: true,
        vowel: false,
        ipa_sym: "k",
        ipa_ent: "&#107;",
        branner: "k",
        number: 109,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: -1,
            DELREL: -1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: -1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: +1,
            LOW: -1,
            FRONT: -1,
            BACK: -1,
            TENSE: 0
        }
    },
    {
        name: "voiced velar stop",
        place: VEL,
        manner: STOP,
        consonant: true,
        vowel: false,
        ipa_sym: "g",
        ipa_ent: "&#609;",
        branner: "g",
        number: 110,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: -1,
            DELREL: -1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: +1,
            LOW: -1,
            FRONT: -1,
            BACK: -1,
            TENSE: 0
        }
    },
    {
        name: "voiced velar nasal",
        place: VEL,
        manner: NASAL,
        consonant: true,
        vowel: false,
        ipa_sym: "ŋ",
        ipa_ent: "&#331;",
        branner: "ng)",
        number: 119,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: +1,
            CONT: -1,
            DELREL: 0,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: +1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: +1,
            LOW: -1,
            FRONT: -1,
            BACK: -1,
            TENSE: 0
        }
    },
    {
        name: "voiceless uvular stop",
        place: UVU,
        manner: STOP,
        consonant: true,
        vowel: false,
        ipa_sym: "q",
        ipa_ent: "&#113;",
        branner: "q",
        number: 111,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: -1,
            DELREL: -1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: -1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: -1,
            LOW: -1,
            FRONT: -1,
            BACK: +1,
            TENSE: 0
        }
    },
    {
        name: "voiced uvular stop",
        place: UVU,
        manner: STOP,
        consonant: true,
        vowel: false,
        ipa_sym: "ɢ",
        ipa_ent: "&#610;",
        branner: "G",
        number: 112,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: -1,
            DELREL: -1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: -1,
            LOW: -1,
            FRONT: -1,
            BACK: +1,
            TENSE: 0
        }
    },
    {
        name: "voiced uvular nasal",
        place: UVU,
        manner: NASAL,
        consonant: true,
        vowel: false,
        ipa_sym: "ɴ",
        ipa_ent: "&#628;",
        branner: "N",
        number: 120,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: +1,
            CONT: -1,
            DELREL: 0,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: +1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: -1,
            LOW: -1,
            FRONT: -1,
            BACK: +1,
            TENSE: 0
        }
    },
    {
        name: "voiceless glottal fricative",
        place: GLOTTAL,
        manner: FRIC,
        consonant: true,
        vowel: false,
        ipa_sym: "h",
        ipa_ent: "&#104;",
        branner: "h",
        number: 146,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: +1,
            DELREL: +1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: -1,
            SP_GLOT: +1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: -1,
            HIGH: 0,
            LOW: 0,
            FRONT: 0,
            BACK: 0,
            TENSE: 0
        }
    },
    {
        name: "voiceless velar fricative",
        place: VEL,
        manner: FRIC,
        consonant: true,
        vowel: false,
        ipa_sym: "x",
        ipa_ent: "&#120;",
        branner: "x",
        number: 140,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: +1,
            DELREL: +1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: -1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: +1,
            LOW: -1,
            FRONT: -1,
            BACK: -1,
            TENSE: 0
        }
    },
    {
        name: "voiced velar fricative",
        place: VEL,
        manner: FRIC,
        consonant: true,
        vowel: false,
        ipa_sym: "ɣ",
        ipa_ent: "&#611;",
        branner: `g"`,
        number: 141,
        features: {
            SYL: -1,
            STRES: -1,
            LONG: -1,
            CONS: +1,
            SON: -1,
            CONT: +1,
            DELREL: +1,
            APPROX: -1,
            TAP: -1,
            TRIL: -1,
            LAT: -1,
            NASAL: -1,
            VOICE: +1,
            SP_GLOT: -1,
            CON_GLOT: -1,
            LABIAL: -1,
            ROUND: -1,
            LAB_DEN: -1,
            CORONAL: -1,
            ANT: 0,
            DISTRO: 0,
            STRID: 0,
            DORSAL: +1,
            HIGH: +1,
            LOW: -1,
            FRONT: -1,
            BACK: -1,
            TENSE: 0
        }
    },
]