import {
    feature,
    ipa_symbol,
    ipa_consonant,
    ipa_vowel,
    ipa_diacritic,
    ipa_letter,
    is_letter,
    LETTER,
    DIAC
} from "./types"
import { get_feature_string } from "./feature_string"

const LABIAL = "labial"
const BILAB = "bilabial"
const LAB_DEN = "labiodental"
const CORONAL = "coronal"
const INTER_DENT = "interdental"
const DENTAL = "dental"
const ALV = "alveolar"
const PAL_ALV = "palatoalveolar"
const RETROFLEX = "retroflex"
const DORSAL = "dorsal"
const PAL = "palatal"
const VEL = "velar"
const UVU = "uvular"
const PHAR = "pharyngeal"
const LARYN = "laryngeal"
const EPIG = "epiglottal"
const GLOTTAL = "glottal"

export const place = {
    LABIAL,
    BILAB,
    LAB_DEN,
    CORONAL,
    INTER_DENT,
    DENTAL,
    ALV,
    PAL_ALV,
    RETROFLEX,
    DORSAL,
    PAL,
    VEL,
    UVU,
    PHAR,
    LARYN,
    EPIG,
    GLOTTAL,
}

export function is_dental(place: string) {
    return (
        place === LABIAL ||
        place === BILAB ||
        place === LAB_DEN
    )
}

export function is_coronal(place: string) {
    return (
        place === CORONAL ||
        place === INTER_DENT ||
        place === DENTAL ||
        place === ALV ||
        place === PAL_ALV ||
        place === RETROFLEX
    )
}

export function is_dorsal(place: string) {
    return (
        place === DORSAL ||
        place === PAL ||
        place === VEL ||
        place === UVU
    )
}

export function is_laryngeal(place: string) {
    return (
        place === LARYN ||
        place === EPIG ||
        place === GLOTTAL
    )
}

const STOP = "stop"
const NASAL = "nasal"
const FRIC = "fricative"
const LAT_FRIC = "lateral fricative"
const AFF = "affricate"
const TRIL = "trill"
const TAP = "tap"
const APPROX = "approximant"
const LAT = "lateral"
const LAT_AFF = "lateral affricate"

export const manner = {
    STOP,
    NASAL,
    FRIC,
    LAT_FRIC,
    AFF,
    TRIL,
    TAP,
    APPROX,
    LAT
}

const SYL = "syllabic"
const STRES = "stress"
const LONG = "long"
const CONS = "consonantal"
const SON = "sonorant"
const CONT = "continuant"
const DELREL = "delayed release"
const VOICE = "voice"
const SP_GLOT = "spread glottis"
const CON_GLOT = "constricted glottis"
const ROUND = "round"
const ANT = "anterior"
const DISTRO = "distributed"
const STRID = "strident"
const HIGH = "high"
const LOW = "low"
const FRONT = "front"
const BACK = "back"
const TENSE = "tense"

export const features = {
    SYL,
    STRES,
    LONG,
    CONS,
    SON,
    CONT,
    DELREL,
    APPROX,
    TAP,
    TRIL,
    LAT,
    NASAL,
    VOICE,
    SP_GLOT,
    CON_GLOT,
    LABIAL,
    ROUND,
    LAB_DEN,
    CORONAL,
    ANT,
    DISTRO,
    STRID,
    DORSAL,
    HIGH,
    LOW,
    FRONT,
    BACK,
    TENSE,
}

function pair_nums(...nums: number[]) {
    let str = ""
    for (let num of nums) {
        str += String(num)
    }
    return parseInt(str, 10)
}

export const glottal_stop: ipa_consonant = {
    name: "glottal stop",
    type: LETTER,
    place: GLOTTAL,
    manner: STOP,
    consonant: true,
    vowel: false,
    ipa_sym: "ʔ",
    ipa_ent: "&#660;",
    branner: "?",
    number: 113,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.neg,
        DELREL: feature.neg,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.neg,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.pos,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const high_front_tense_unround_vowel: ipa_vowel = {
    name: "high front tense unrounded vowel",
    type: LETTER,
    place: DORSAL,
    consonant: false,
    vowel: true,
    ipa_sym: "i",
    ipa_ent: "&#105;",
    branner: "i",
    number: 301,
    features: {
        SYL: feature.pos,
        CONS: feature.neg,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.pos,
        LOW: feature.neg,
        FRONT: feature.pos,
        BACK: feature.neg,
        TENSE: feature.pos,
    }
}

export const high_front_tense_round_vowel: ipa_vowel = {
    name: "high front tense rounded vowel",
    type: LETTER,
    place: DORSAL,
    consonant: false,
    vowel: true,
    ipa_sym: "y",
    ipa_ent: "&#121;",
    branner: "y",
    number: 309,
    features: {
        SYL: feature.pos,
        CONS: feature.neg,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.pos,
        ROUND: feature.pos,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.pos,
        LOW: feature.neg,
        FRONT: feature.pos,
        BACK: feature.neg,
        TENSE: feature.pos,
    }
}

export const near_high_front_lax_unround_vowel: ipa_vowel = {
    name: "near-high front lax unrounded vowel",
    type: LETTER,
    place: DORSAL,
    consonant: false,
    vowel: true,
    ipa_sym: "ɪ",
    ipa_ent: "&#618;",
    branner: "I",
    number: 319,
    features: {
        SYL: feature.pos,
        CONS: feature.neg,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.pos,
        LOW: feature.neg,
        FRONT: feature.pos,
        BACK: feature.neg,
        TENSE: feature.neg,
    }
}

export const near_high_front_lax_round_vowel: ipa_vowel = {
    name: "near-high front lax rounded vowel",
    type: LETTER,
    place: DORSAL,
    consonant: false,
    vowel: true,
    ipa_sym: "ʏ",
    ipa_ent: "&#655;",
    branner: "Y",
    number: 320,
    features: {
        SYL: feature.pos,
        CONS: feature.neg,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.pos,
        ROUND: feature.pos,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.pos,
        LOW: feature.neg,
        FRONT: feature.pos,
        BACK: feature.neg,
        TENSE: feature.neg,
    }
}

export const high_mid_front_tense_unround_vowel: ipa_vowel = {
    name: "high-mid front tense unrounded vowel",
    type: LETTER,
    place: DORSAL,
    consonant: false,
    vowel: true,
    ipa_sym: "e",
    ipa_ent: "&#101;",
    branner: "e",
    number: 302,
    features: {
        SYL: feature.pos,
        CONS: feature.neg,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.neg,
        LOW: feature.neg,
        FRONT: feature.pos,
        BACK: feature.neg,
        TENSE: feature.pos,
    }
}

export const high_mid_front_tense_round_vowel: ipa_vowel = {
    name: "high-mid front tense rounded vowel",
    type: LETTER,
    place: DORSAL,
    consonant: false,
    vowel: true,
    ipa_sym: "ø",
    ipa_ent: "&#248;",
    branner: "o/)",
    number: 310,
    features: {
        SYL: feature.pos,
        CONS: feature.neg,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.pos,
        ROUND: feature.pos,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.neg,
        LOW: feature.neg,
        FRONT: feature.pos,
        BACK: feature.neg,
        TENSE: feature.pos,
    }
}

export const low_mid_front_unround_vowel: ipa_vowel = {
    name: "low-mid front unrounded vowel",
    type: LETTER,
    place: DORSAL,
    consonant: false,
    vowel: true,
    ipa_sym: "ε",
    ipa_ent: "&#603;",
    branner: "E",
    number: 303,
    features: {
        SYL: feature.pos,
        CONS: feature.neg,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.neg,
        LOW: feature.neg,
        FRONT: feature.pos,
        BACK: feature.neg,
        TENSE: feature.neg,
    }
}

export const low_mid_front_round_vowel: ipa_vowel = {
    name: "low-mid front rounded vowel",
    type: LETTER,
    place: DORSAL,
    consonant: false,
    vowel: true,
    ipa_sym: "œ",
    ipa_ent: "&#339;",
    branner: "oe)",
    number: 311,
    features: {
        SYL: feature.pos,
        CONS: feature.neg,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.pos,
        ROUND: feature.pos,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.neg,
        LOW: feature.neg,
        FRONT: feature.pos,
        BACK: feature.neg,
        TENSE: feature.neg,
    }
}

export const near_low_front_unround_vowel: ipa_vowel = {
    name: "near-low front unrounded vowel",
    type: LETTER,
    place: DORSAL,
    consonant: false,
    vowel: true,
    ipa_sym: "æ",
    ipa_ent: "&#230;",
    branner: "ae)",
    number: 325,
    features: {
        SYL: feature.pos,
        CONS: feature.neg,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.neg,
        LOW: feature.pos,
        FRONT: feature.pos,
        BACK: feature.neg,
        TENSE: feature.pos,
    }
}

export const low_front_unround_vowel: ipa_vowel = {
    name: "low front unrounded vowel",
    type: LETTER,
    place: DORSAL,
    consonant: false,
    vowel: true,
    ipa_sym: "a",
    ipa_ent: "&#97;",
    branner: "a",
    number: 304,
    features: {
        SYL: feature.pos,
        CONS: feature.neg,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.neg,
        LOW: feature.pos,
        FRONT: feature.pos,
        BACK: feature.neg,
        TENSE: feature.zero,
    }
}

export const low_front_round_vowel: ipa_vowel = {
    name: "low front rounded vowel",
    type: LETTER,
    place: DORSAL,
    consonant: false,
    vowel: true,
    ipa_sym: "Œ",
    ipa_ent: "&#630;",
    branner: "OE)",
    number: 312,
    features: {
        SYL: feature.pos,
        CONS: feature.neg,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.pos,
        ROUND: feature.pos,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.neg,
        LOW: feature.pos,
        FRONT: feature.pos,
        BACK: feature.neg,
        TENSE: feature.zero,
    }
}

export const high_central_tense_unround_vowel: ipa_vowel = {
    name: "high central tense unrounded vowel",
    type: LETTER,
    place: DORSAL,
    consonant: false,
    vowel: true,
    ipa_sym: "ɨ",
    ipa_ent: "&#616;",
    branner: "i-",
    number: 317,
    features: {
        SYL: feature.pos,
        CONS: feature.neg,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.pos,
        LOW: feature.neg,
        FRONT: feature.neg,
        BACK: feature.neg,
        TENSE: feature.pos,
    }
}

export const high_central_tense_round_vowel: ipa_vowel = {
    name: "high central tense rounded vowel",
    type: LETTER,
    place: DORSAL,
    consonant: false,
    vowel: true,
    ipa_sym: "ʉ",
    ipa_ent: "&#649;",
    branner: "u-",
    number: 318,
    features: {
        SYL: feature.pos,
        CONS: feature.neg,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.pos,
        ROUND: feature.pos,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.pos,
        LOW: feature.neg,
        FRONT: feature.neg,
        BACK: feature.neg,
        TENSE: feature.pos,
    }
}

export const schwa: ipa_vowel = {
    name: "schwa",
    type: LETTER,
    place: DORSAL,
    consonant: false,
    vowel: true,
    ipa_sym: "ə",
    ipa_ent: "&#601;",
    branner: "@",
    number: 322,
    features: {
        SYL: feature.pos,
        CONS: feature.neg,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.neg,
        LOW: feature.neg,
        FRONT: feature.neg,
        BACK: feature.neg,
        TENSE: feature.neg,
    }
}

export const high_back_tense_unround_vowel: ipa_vowel = {
    name: "high back tense unrounded vowel",
    type: LETTER,
    place: DORSAL,
    consonant: false,
    vowel: true,
    ipa_sym: "ɯ",
    ipa_ent: "&#623;",
    branner: "m&",
    number: 316,
    features: {
        SYL: feature.pos,
        CONS: feature.neg,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.pos,
        LOW: feature.neg,
        FRONT: feature.neg,
        BACK: feature.pos,
        TENSE: feature.pos,
    }
}

export const high_back_tense_round_vowel: ipa_vowel = {
    name: "high back tense rounded vowel",
    type: LETTER,
    place: DORSAL,
    consonant: false,
    vowel: true,
    ipa_sym: "u",
    ipa_ent: "&#117;",
    branner: "u",
    number: 308,
    features: {
        SYL: feature.pos,
        CONS: feature.neg,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.pos,
        ROUND: feature.pos,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.pos,
        LOW: feature.neg,
        FRONT: feature.neg,
        BACK: feature.pos,
        TENSE: feature.pos,
    }
}

export const near_high_back_lax_round_vowel: ipa_vowel = {
    name: "near-high back lax rounded vowel",
    type: LETTER,
    place: DORSAL,
    consonant: false,
    vowel: true,
    ipa_sym: "ʊ",
    ipa_ent: "&#650;",
    branner: "U",
    number: 321,
    features: {
        SYL: feature.pos,
        CONS: feature.neg,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.pos,
        ROUND: feature.pos,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.pos,
        LOW: feature.neg,
        FRONT: feature.neg,
        BACK: feature.pos,
        TENSE: feature.neg,
    }
}

export const high_mid_back_tense_unround_vowel: ipa_vowel = {
    name: "high-mid back tense unrounded vowel",
    type: LETTER,
    place: DORSAL,
    consonant: false,
    vowel: true,
    ipa_sym: "ɤ",
    ipa_ent: "&#612;",
    branner: `U"`,
    number: 315,
    features: {
        SYL: feature.pos,
        CONS: feature.neg,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.neg,
        LOW: feature.neg,
        FRONT: feature.neg,
        BACK: feature.pos,
        TENSE: feature.pos,
    }
}

export const high_mid_back_tense_round_vowel: ipa_vowel = {
    name: "high-mid back tense rounded vowel",
    type: LETTER,
    place: DORSAL,
    consonant: false,
    vowel: true,
    ipa_sym: "o",
    ipa_ent: "&#111;",
    branner: "o",
    number: 307,
    features: {
        SYL: feature.pos,
        CONS: feature.neg,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.pos,
        ROUND: feature.pos,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.neg,
        LOW: feature.neg,
        FRONT: feature.neg,
        BACK: feature.pos,
        TENSE: feature.pos,
    }
}

export const low_mid_back_lax_unround_vowel: ipa_vowel = {
    name: "low-mid back lax unrounded vowel",
    type: LETTER,
    place: DORSAL,
    consonant: false,
    vowel: true,
    ipa_sym: "ʌ",
    ipa_ent: "&#652;",
    branner: "v&",
    number: 314,
    features: {
        SYL: feature.pos,
        CONS: feature.neg,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.neg,
        LOW: feature.neg,
        FRONT: feature.neg,
        BACK: feature.pos,
        TENSE: feature.neg,
    }
}

export const low_mid_back_lax_round_vowel: ipa_vowel = {
    name: "low-mid back lax rounded vowel",
    type: LETTER,
    place: DORSAL,
    consonant: false,
    vowel: true,
    ipa_sym: "ɔ",
    ipa_ent: "&#596;",
    branner: "c&",
    number: 306,
    features: {
        SYL: feature.pos,
        CONS: feature.neg,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.pos,
        ROUND: feature.pos,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.neg,
        LOW: feature.neg,
        FRONT: feature.neg,
        BACK: feature.pos,
        TENSE: feature.neg,
    }
}

export const low_back_unround_vowel: ipa_vowel = {
    name: "low back unrounded vowel",
    type: LETTER,
    place: DORSAL,
    consonant: false,
    vowel: true,
    ipa_sym: "ɑ",
    ipa_ent: "&#593;",
    branner: `a"`,
    number: 305,
    features: {
        SYL: feature.pos,
        CONS: feature.neg,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.neg,
        LOW: feature.pos,
        FRONT: feature.neg,
        BACK: feature.pos,
        TENSE: feature.zero,
    }
}

export const low_back_round_vowel: ipa_vowel = {
    name: "low back rounded vowel",
    type: LETTER,
    place: DORSAL,
    consonant: false,
    vowel: true,
    ipa_sym: "ɒ",
    ipa_ent: "&#594;",
    branner: `a"&`,
    number: 313,
    features: {
        SYL: feature.pos,
        CONS: feature.neg,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.pos,
        ROUND: feature.pos,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.neg,
        LOW: feature.pos,
        FRONT: feature.neg,
        BACK: feature.pos,
        TENSE: feature.zero,
    }
}

export const voiceless_bilabial_stop: ipa_consonant = {
    name: "voiceless bilabial stop",
    type: LETTER,
    place: BILAB,
    manner: STOP,
    consonant: true,
    vowel: false,
    ipa_sym: "p",
    ipa_ent: "&#112;",
    branner: "p",
    number: 101,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.neg,
        DELREL: feature.neg,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.neg,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.pos,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiced_bilabial_stop: ipa_consonant = {
    name: "voiced bilabial stop",
    type: LETTER,
    place: BILAB,
    manner: STOP,
    consonant: true,
    vowel: false,
    ipa_sym: "b",
    ipa_ent: "&#98;",
    branner: "b",
    number: 102,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.neg,
        DELREL: feature.neg,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.pos,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiced_bilabial_nasal: ipa_consonant = {
    name: "voiced bilabial nasal",
    type: LETTER,
    place: BILAB,
    manner: NASAL,
    consonant: true,
    vowel: false,
    ipa_sym: "m",
    ipa_ent: "&#109;",
    branner: "m",
    number: 114,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.pos,
        CONT: feature.neg,
        DELREL: feature.zero,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.pos,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.pos,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiceless_bilabial_nasal: ipa_consonant = {
    name: "voiceless bilabial nasal",
    type: LETTER,
    place: BILAB,
    manner: NASAL,
    consonant: true,
    vowel: false,
    ipa_sym: "m̥",
    ipa_ent: "&#109;&#805;",
    branner: "mV)",
    number: pair_nums(114, 402),
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.pos,
        CONT: feature.neg,
        DELREL: feature.zero,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.pos,
        VOICE: feature.neg,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.pos,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiceless_bilabial_fricative: ipa_consonant = {
    name: "voiceless bilabial fricative",
    type: LETTER,
    place: BILAB,
    manner: FRIC,
    consonant: true,
    vowel: false,
    ipa_sym: "ɸ",
    ipa_ent: "&#632;",
    branner: `P"`,
    number: 126,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.pos,
        DELREL: feature.pos,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.neg,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.pos,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiced_bilabial_fricative: ipa_consonant = {
    name: "voiced bilabial fricative",
    type: LETTER,
    place: BILAB,
    manner: FRIC,
    consonant: true,
    vowel: false,
    ipa_sym: "β",
    ipa_ent: "&#946;",
    branner: `B"`,
    number: 127,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.pos,
        DELREL: feature.pos,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.pos,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiced_bilabial_trill: ipa_consonant = {
    name: "voiced bilabial trill",
    type: LETTER,
    place: BILAB,
    manner: TRIL,
    consonant: true,
    vowel: false,
    ipa_sym: "ʙ",
    ipa_ent: "&#665;",
    branner: "B",
    number: 121,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.pos,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.pos,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiceless_bilabial_trill: ipa_consonant = {
    name: "voiceless bilabial trill",
    type: LETTER,
    place: BILAB,
    manner: TRIL,
    consonant: true,
    vowel: false,
    ipa_sym: "ʙ̥",
    ipa_ent: "&#665;&#805;",
    branner: "BV)",
    number: pair_nums(121, 402),
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.pos,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.neg,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.pos,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiceless_labiodental_affricate: ipa_consonant = {
    name: "voiceless labiodental affricate",
    type: LETTER,
    place: LAB_DEN,
    manner: AFF,
    consonant: true,
    vowel: false,
    ipa_sym: "p̪͡f",
    ipa_ent: "&#112;&#810;&#865;&#102;",
    branner: "p[f))",
    number: pair_nums(101, 408, 128),
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.neg,
        DELREL: feature.pos,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.neg,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.pos,
        ROUND: feature.neg,
        LAB_DEN: feature.pos,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiced_labiodental_affricate: ipa_consonant = {
    name: "voiced labiodental affricate",
    type: LETTER,
    place: LAB_DEN,
    manner: AFF,
    consonant: true,
    vowel: false,
    ipa_sym: "b̪͡v",
    ipa_ent: "&#98;&#810;&#865;&#118;",
    branner: "b[v))",
    number: pair_nums(102, 408, 129),
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.neg,
        DELREL: feature.pos,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.pos,
        ROUND: feature.neg,
        LAB_DEN: feature.pos,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiced_labiodental_nasal: ipa_consonant = {
    name: "voiced labiodental nasal",
    type: LETTER,
    place: LAB_DEN,
    manner: NASAL,
    consonant: true,
    vowel: false,
    ipa_sym: "ɱ",
    ipa_ent: "&#625;",
    branner: `m"`,
    number: 115,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.pos,
        CONT: feature.neg,
        DELREL: feature.zero,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.pos,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.pos,
        ROUND: feature.neg,
        LAB_DEN: feature.pos,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiceless_labiodental_fricative: ipa_consonant = {
    name: "voiceless labiodental fricative",
    type: LETTER,
    place: LAB_DEN,
    manner: FRIC,
    consonant: true,
    vowel: false,
    ipa_sym: "f",
    ipa_ent: "&#102;",
    branner: "f",
    number: 128,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.pos,
        DELREL: feature.pos,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.neg,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.pos,
        ROUND: feature.neg,
        LAB_DEN: feature.pos,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiced_labiodental_fricative: ipa_consonant = {
    name: "voiced labiodental fricative",
    type: LETTER,
    place: LAB_DEN,
    manner: FRIC,
    consonant: true,
    vowel: false,
    ipa_sym: "v",
    ipa_ent: "&#118;",
    branner: "v",
    number: 129,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.pos,
        DELREL: feature.pos,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.pos,
        ROUND: feature.neg,
        LAB_DEN: feature.pos,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiced_labiodental_approximant: ipa_consonant = {
    name: "voiced labiodental approximant",
    type: LETTER,
    place: LAB_DEN,
    manner: APPROX,
    consonant: true,
    vowel: false,
    ipa_sym: "ʋ",
    ipa_ent: "&#651;",
    branner: `v"`,
    number: 150,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.pos,
        ROUND: feature.neg,
        LAB_DEN: feature.pos,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiceless_alveolar_stop: ipa_consonant = {
    name: "voiceless alveolar stop",
    type: LETTER,
    place: ALV,
    manner: STOP,
    consonant: true,
    vowel: false,
    ipa_sym: "t",
    ipa_ent: "&#116;",
    branner: "t",
    number: 103,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.neg,
        DELREL: feature.neg,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.neg,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.pos,
        ANT: feature.pos,
        DISTRO: feature.neg,
        STRID: feature.neg,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiced_alveolar_stop: ipa_consonant = {
    name: "voiced alveolar stop",
    type: LETTER,
    place: ALV,
    manner: STOP,
    consonant: true,
    vowel: false,
    ipa_sym: "d",
    ipa_ent: "&#100;",
    branner: "d",
    number: 104,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.neg,
        DELREL: feature.neg,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.pos,
        ANT: feature.pos,
        DISTRO: feature.neg,
        STRID: feature.neg,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiceless_dental_stop: ipa_consonant = {
    name: "voiceless dental stop",
    type: LETTER,
    place: DENTAL,
    manner: STOP,
    consonant: true,
    vowel: false,
    ipa_sym: "t̪",
    ipa_ent: "&#116;&#810;",
    branner: "t[",
    number: pair_nums(103, 408),
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.neg,
        DELREL: feature.neg,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.neg,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.pos,
        ANT: feature.pos,
        DISTRO: feature.pos,
        STRID: feature.neg,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiced_dental_stop: ipa_consonant = {
    name: "voiced dental stop",
    type: LETTER,
    place: DENTAL,
    manner: STOP,
    consonant: true,
    vowel: false,
    ipa_sym: "d̪",
    ipa_ent: "&#100;&#810;",
    branner: "d[",
    number: pair_nums(104, 408),
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.neg,
        DELREL: feature.neg,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.pos,
        ANT: feature.pos,
        DISTRO: feature.pos,
        STRID: feature.neg,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiceless_dental_fricative: ipa_consonant = {
    name: "voiceless dental fricative",
    type: LETTER,
    place: INTER_DENT,
    manner: FRIC,
    consonant: true,
    vowel: false,
    ipa_sym: "θ",
    ipa_ent: "&#952;",
    branner: "0-",
    number: 130,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.pos,
        DELREL: feature.pos,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.neg,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.pos,
        ANT: feature.pos,
        DISTRO: feature.pos,
        STRID: feature.neg,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiced_dental_fricative: ipa_consonant = {
    name: "voiced dental fricative",
    type: LETTER,
    place: INTER_DENT,
    manner: FRIC,
    consonant: true,
    vowel: false,
    ipa_sym: "ð",
    ipa_ent: "&#240;",
    branner: "d-",
    number: 131,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.pos,
        DELREL: feature.pos,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.pos,
        ANT: feature.pos,
        DISTRO: feature.pos,
        STRID: feature.neg,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiced_alveolar_nasal: ipa_consonant = {
    name: "voiced alveolar nasal",
    type: LETTER,
    place: ALV,
    manner: NASAL,
    consonant: true,
    vowel: false,
    ipa_sym: "n",
    ipa_ent: "&#110;",
    branner: "n",
    number: 116,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.pos,
        CONT: feature.neg,
        DELREL: feature.zero,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.pos,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.pos,
        ANT: feature.pos,
        DISTRO: feature.neg,
        STRID: feature.neg,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiceless_alveolar_affricate: ipa_consonant = {
    name: "voiceless alveolar affricate",
    type: LETTER,
    place: ALV,
    manner: AFF,
    consonant: true,
    vowel: false,
    ipa_sym: "t͡s",
    ipa_ent: "&#116;&#865;&#115;",
    branner: "ts))",
    number: pair_nums(103, 132),
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.neg,
        DELREL: feature.pos,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.neg,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.pos,
        ANT: feature.pos,
        DISTRO: feature.neg,
        STRID: feature.pos,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiced_alveolar_affricate: ipa_consonant = {
    name: "voiced alveolar affricate",
    type: LETTER,
    place: ALV,
    manner: AFF,
    consonant: true,
    vowel: false,
    ipa_sym: "d͡z",
    ipa_ent: "&#100;&#865;&#122;",
    branner: "dz))",
    number: pair_nums(104, 133),
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.neg,
        DELREL: feature.pos,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.pos,
        ANT: feature.pos,
        DISTRO: feature.neg,
        STRID: feature.pos,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiceless_alveolar_fricative: ipa_consonant = {
    name: "voiceless alveolar fricative",
    type: LETTER,
    place: ALV,
    manner: FRIC,
    consonant: true,
    vowel: false,
    ipa_sym: "s",
    ipa_ent: "&#115;",
    branner: "s",
    number: 132,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.pos,
        DELREL: feature.pos,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.neg,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.pos,
        ANT: feature.pos,
        DISTRO: feature.neg,
        STRID: feature.pos,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiced_alveolar_fricative: ipa_consonant = {
    name: "voiced alveolar fricative",
    type: LETTER,
    place: ALV,
    manner: FRIC,
    consonant: true,
    vowel: false,
    ipa_sym: "z",
    ipa_ent: "&#122;",
    branner: "z",
    number: 133,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.pos,
        DELREL: feature.pos,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.pos,
        ANT: feature.pos,
        DISTRO: feature.neg,
        STRID: feature.pos,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiceless_alveolar_lat_affricate: ipa_consonant = {
    name: "voiceless alveolar lateral affricate",
    type: LETTER,
    place: ALV,
    manner: LAT_AFF,
    consonant: true,
    vowel: false,
    ipa_sym: "t͡ɬ",
    ipa_ent: "&#116;&#865;&#620;",
    branner: "tl-))",
    number: pair_nums(103, 148),
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.neg,
        DELREL: feature.pos,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.neg,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.pos,
        ANT: feature.pos,
        DISTRO: feature.neg,
        STRID: feature.pos,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiced_alveolar_lat_affricate: ipa_consonant = {
    name: "voiced alveolar lateral affricate",
    type: LETTER,
    place: ALV,
    manner: LAT_AFF,
    consonant: true,
    vowel: false,
    ipa_sym: "d͡ɮ",
    ipa_ent: "&#100;&#865;&#622;",
    branner: `dl3")))`,
    number: pair_nums(104, 149),
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.neg,
        DELREL: feature.pos,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.pos,
        ANT: feature.pos,
        DISTRO: feature.neg,
        STRID: feature.pos,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiceless_alveolar_lat_fric: ipa_consonant = {
    name: "voiceless alveolar lateral fricative",
    type: LETTER,
    place: ALV,
    manner: LAT_FRIC,
    consonant: true,
    vowel: false,
    ipa_sym: "ɬ",
    ipa_ent: "&#620;",
    branner: "l-",
    number: 148,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.pos,
        DELREL: feature.pos,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.pos,
        NASAL: feature.neg,
        VOICE: feature.neg,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.pos,
        ANT: feature.pos,
        DISTRO: feature.neg,
        STRID: feature.neg,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiced_alveolar_lat_fric: ipa_consonant = {
    name: "voiced alveolar lateral fricative",
    type: LETTER,
    place: ALV,
    manner: LAT_FRIC,
    consonant: true,
    vowel: false,
    ipa_sym: "ɮ",
    ipa_ent: "&#622;",
    branner: `l3")`,
    number: 149,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.pos,
        DELREL: feature.pos,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.pos,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.pos,
        ANT: feature.pos,
        DISTRO: feature.neg,
        STRID: feature.neg,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiced_alveolar_approx: ipa_consonant = {
    name: "voiced alveolar approximant",
    type: LETTER,
    place: ALV,
    manner: APPROX,
    consonant: true,
    vowel: false,
    ipa_sym: "ɹ",
    ipa_ent: "&#633;",
    branner: "r&",
    number: 151,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.pos,
        ANT: feature.neg,
        DISTRO: feature.pos,
        STRID: feature.neg,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiced_alveolar_trill: ipa_consonant = {
    name: "voiced alveolar trill",
    type: LETTER,
    place: ALV,
    manner: TRIL,
    consonant: true,
    vowel: false,
    ipa_sym: "r",
    ipa_ent: "&#114;",
    branner: "r",
    number: 122,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.pos,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.pos,
        ANT: feature.pos,
        DISTRO: feature.neg,
        STRID: feature.neg,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiced_alveolar_tap: ipa_consonant = {
    name: "voiced alveolar tap",
    type: LETTER,
    place: ALV,
    manner: TAP,
    consonant: true,
    vowel: false,
    ipa_sym: "ɾ",
    ipa_ent: "&#638;",
    branner: `r"`,
    number: 124,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.pos,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.pos,
        ANT: feature.pos,
        DISTRO: feature.neg,
        STRID: feature.neg,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiced_alveolar_lateral: ipa_consonant = {
    name: "voiced alveolar lateral",
    type: LETTER,
    place: ALV,
    manner: LAT,
    consonant: true,
    vowel: false,
    ipa_sym: "l",
    ipa_ent: "&#108;",
    branner: "l",
    number: 155,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.pos,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.pos,
        ANT: feature.pos,
        DISTRO: feature.neg,
        STRID: feature.neg,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const dark_l: ipa_consonant = {
    name: "dark l",
    type: LETTER,
    place: ALV,
    manner: LAT,
    consonant: true,
    vowel: false,
    ipa_sym: "ɫ",
    ipa_ent: "&#619;",
    branner: "l~)",
    number: 209,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.pos,
        CONT: feature.pos,
        DELREL: feature.zero,
        APPROX: feature.pos,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.pos,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.pos,
        ANT: feature.pos,
        DISTRO: feature.neg,
        STRID: feature.neg,
        DORSAL: feature.pos,
        HIGH: feature.pos,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.pos,
        TENSE: feature.zero
    }
}

export const voiceless_pal_alv_affricate: ipa_consonant = {
    name: "voiceless palatoalveolar affricate",
    type: LETTER,
    place: PAL_ALV,
    manner: AFF,
    consonant: true,
    vowel: false,
    ipa_sym: "t͡ʃ",
    ipa_ent: "&#116;&#865;&#643;",
    branner: "tS))",
    number: pair_nums(103, 134),
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.neg,
        DELREL: feature.pos,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.neg,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.pos,
        ANT: feature.neg,
        DISTRO: feature.pos,
        STRID: feature.pos,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiced_pal_alv_affricate: ipa_consonant = {
    name: "voiced palatoalveolar affricate",
    type: LETTER,
    place: PAL_ALV,
    manner: AFF,
    consonant: true,
    vowel: false,
    ipa_sym: "d͡ʒ",
    ipa_ent: "&#100;&#865;&#658;",
    branner: `d3"))`,
    number: pair_nums(104, 135),
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.neg,
        DELREL: feature.pos,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.pos,
        ANT: feature.neg,
        DISTRO: feature.pos,
        STRID: feature.pos,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiceless_pal_alv_fricative: ipa_consonant = {
    name: "voiceless palatoalveolar fricative",
    type: LETTER,
    place: PAL_ALV,
    manner: FRIC,
    consonant: true,
    vowel: false,
    ipa_sym: "ʃ",
    ipa_ent: "&#643;",
    branner: "S",
    number: 134,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.pos,
        DELREL: feature.pos,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.neg,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.pos,
        ANT: feature.neg,
        DISTRO: feature.pos,
        STRID: feature.pos,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiced_pal_alv_fricative = {
    name: "voiced palatoalveolar fricative",
    type: LETTER,
    place: PAL_ALV,
    manner: FRIC,
    consonant: true,
    vowel: false,
    ipa_sym: "ʒ",
    ipa_ent: "&#658;",
    branner: `3"`,
    number: 135,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.pos,
        DELREL: feature.pos,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.pos,
        ANT: feature.neg,
        DISTRO: feature.pos,
        STRID: feature.pos,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiceless_velar_stop: ipa_consonant = {
    name: "voiceless velar stop",
    type: LETTER,
    place: VEL,
    manner: STOP,
    consonant: true,
    vowel: false,
    ipa_sym: "k",
    ipa_ent: "&#107;",
    branner: "k",
    number: 109,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.neg,
        DELREL: feature.neg,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.neg,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.pos,
        LOW: feature.neg,
        FRONT: feature.neg,
        BACK: feature.neg,
        TENSE: feature.zero
    }
}

export const voiced_velar_stop: ipa_consonant = {
    name: "voiced velar stop",
    type: LETTER,
    place: VEL,
    manner: STOP,
    consonant: true,
    vowel: false,
    ipa_sym: "g",
    ipa_ent: "&#609;",
    branner: "g",
    number: 110,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.neg,
        DELREL: feature.neg,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.pos,
        LOW: feature.neg,
        FRONT: feature.neg,
        BACK: feature.neg,
        TENSE: feature.zero
    }
}

export const voiced_velar_nasal: ipa_consonant = {
    name: "voiced velar nasal",
    type: LETTER,
    place: VEL,
    manner: NASAL,
    consonant: true,
    vowel: false,
    ipa_sym: "ŋ",
    ipa_ent: "&#331;",
    branner: "ng)",
    number: 119,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.pos,
        CONT: feature.neg,
        DELREL: feature.zero,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.pos,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.pos,
        LOW: feature.neg,
        FRONT: feature.neg,
        BACK: feature.neg,
        TENSE: feature.zero
    }
}

export const voiceless_uvular_stop = {
    name: "voiceless uvular stop",
    type: LETTER,
    place: UVU,
    manner: STOP,
    consonant: true,
    vowel: false,
    ipa_sym: "q",
    ipa_ent: "&#113;",
    branner: "q",
    number: 111,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.neg,
        DELREL: feature.neg,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.neg,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.neg,
        LOW: feature.neg,
        FRONT: feature.neg,
        BACK: feature.pos,
        TENSE: feature.zero
    }
}

export const voiced_uvular_stop = {
    name: "voiced uvular stop",
    type: LETTER,
    place: UVU,
    manner: STOP,
    consonant: true,
    vowel: false,
    ipa_sym: "ɢ",
    ipa_ent: "&#610;",
    branner: "G",
    number: 112,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.neg,
        DELREL: feature.neg,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.neg,
        LOW: feature.neg,
        FRONT: feature.neg,
        BACK: feature.pos,
        TENSE: feature.zero
    }
}

export const voiced_uvular_nasal: ipa_consonant = {
    name: "voiced uvular nasal",
    type: LETTER,
    place: UVU,
    manner: NASAL,
    consonant: true,
    vowel: false,
    ipa_sym: "ɴ",
    ipa_ent: "&#628;",
    branner: "N",
    number: 120,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.pos,
        CONT: feature.neg,
        DELREL: feature.zero,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.pos,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.neg,
        LOW: feature.neg,
        FRONT: feature.neg,
        BACK: feature.pos,
        TENSE: feature.zero
    }
}

export const voiceless_glottal_fricative: ipa_consonant = {
    name: "voiceless glottal fricative",
    type: LETTER,
    place: GLOTTAL,
    manner: FRIC,
    consonant: true,
    vowel: false,
    ipa_sym: "h",
    ipa_ent: "&#104;",
    branner: "h",
    number: 146,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.pos,
        DELREL: feature.pos,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.neg,
        SP_GLOT: feature.pos,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.neg,
        HIGH: feature.zero,
        LOW: feature.zero,
        FRONT: feature.zero,
        BACK: feature.zero,
        TENSE: feature.zero
    }
}

export const voiceless_velar_fricative: ipa_consonant = {
    name: "voiceless velar fricative",
    type: LETTER,
    place: VEL,
    manner: FRIC,
    consonant: true,
    vowel: false,
    ipa_sym: "x",
    ipa_ent: "&#120;",
    branner: "x",
    number: 140,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.pos,
        DELREL: feature.pos,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.neg,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.pos,
        LOW: feature.neg,
        FRONT: feature.neg,
        BACK: feature.neg,
        TENSE: feature.zero
    }
}

export const voiced_velar_fricative: ipa_consonant = {
    name: "voiced velar fricative",
    type: LETTER,
    place: VEL,
    manner: FRIC,
    consonant: true,
    vowel: false,
    ipa_sym: "ɣ",
    ipa_ent: "&#611;",
    branner: `g"`,
    number: 141,
    features: {
        SYL: feature.neg,
        CONS: feature.pos,
        SON: feature.neg,
        CONT: feature.pos,
        DELREL: feature.pos,
        APPROX: feature.neg,
        TAP: feature.neg,
        TRIL: feature.neg,
        LAT: feature.neg,
        NASAL: feature.neg,
        VOICE: feature.pos,
        SP_GLOT: feature.neg,
        CON_GLOT: feature.neg,
        LABIAL: feature.neg,
        ROUND: feature.neg,
        LAB_DEN: feature.neg,
        CORONAL: feature.neg,
        ANT: feature.zero,
        DISTRO: feature.zero,
        STRID: feature.zero,
        DORSAL: feature.pos,
        HIGH: feature.pos,
        LOW: feature.neg,
        FRONT: feature.neg,
        BACK: feature.neg,
        TENSE: feature.zero
    }
}

export const syllable_break: ipa_diacritic = {
    name: "syllable break",
    type: DIAC,
    ipa_sym: ".",
    ipa_ent: "&#46;",
    branner: ".",
    number: 506
}

export const primary_stress: ipa_diacritic = {
    name: "primary stress",
    type: DIAC,
    ipa_sym: "ˈ",
    ipa_ent: "&#712;",
    branner: "'",
    number: 501
}

export const secondary_stress: ipa_diacritic = {
    name: "secondary stress",
    type: DIAC,
    ipa_sym: "ˌ",
    ipa_ent: "&#716;",
    branner: ",",
    number: 502
}

export const long: ipa_diacritic = {
    name: "long",
    type: DIAC,
    ipa_sym: "ː",
    ipa_ent: "&#720;",
    branner: ":",
    number: 503
}

export const half_long: ipa_diacritic = {
    name: "half long",
    type: DIAC,
    ipa_sym: "ˑ",
    ipa_ent: "&#721;",
    branner: ";",
    number: 504
}

// NOTE: The diacritics come in two forms:
// combining and non-combining. I am using the
// combining variant because that is what I am
// expecting as user input. Due to this file itself
// being written in Unicode, it will appear strangely
// but the tests will show the symbol is still there.
export const top_diacritic: ipa_diacritic = {
    name: "top diacritic",
    type: DIAC,
    ipa_sym: `̋`,
    ipa_ent: "&#779;",
    branner: "5",
    number: 512
}

export const high_diacritic: ipa_diacritic = {
    name: "high diacritic",
    type: DIAC,
    ipa_sym: `́`,
    ipa_ent: "&#769;",
    branner: "4",
    number: 513
}

export const mid_diacritic: ipa_diacritic = {
    name: "mid diacritic",
    type: DIAC,
    ipa_sym: `̄`,
    ipa_ent: "&#772;",
    branner: "3",
    number: 514
}

export const low_diacritic: ipa_diacritic = {
    name: "low diacritic",
    type: DIAC,
    ipa_sym: `̄`,
    ipa_ent: "&#768;",
    branner: "2",
    number: 515
}

export const bottom_diacritic: ipa_diacritic = {
    name: "bottom diacritic",
    type: DIAC,
    ipa_sym: `̏`,
    ipa_ent: "&#783;",
    branner: "1",
    number: 516
}

const all_phones: ipa_symbol[] = [
    high_front_tense_unround_vowel,
    high_front_tense_round_vowel,
    near_high_front_lax_unround_vowel,
    near_high_front_lax_round_vowel,
    high_mid_front_tense_unround_vowel,
    high_mid_front_tense_round_vowel,
    low_mid_front_unround_vowel,
    low_mid_front_round_vowel,
    near_low_front_unround_vowel,
    low_front_unround_vowel,
    low_front_round_vowel,
    high_central_tense_unround_vowel,
    high_central_tense_round_vowel,
    schwa,
    high_back_tense_unround_vowel,
    high_back_tense_round_vowel,
    near_high_back_lax_round_vowel,
    high_mid_back_tense_unround_vowel,
    high_mid_back_tense_round_vowel,
    low_mid_back_lax_unround_vowel,
    low_mid_back_lax_round_vowel,
    low_back_unround_vowel,
    low_back_round_vowel,
    voiceless_bilabial_stop,
    voiced_bilabial_stop,
    voiced_bilabial_nasal,
    voiceless_bilabial_nasal,
    voiceless_bilabial_fricative,
    voiced_bilabial_fricative,
    voiced_bilabial_trill,
    voiceless_bilabial_trill,
    voiceless_labiodental_affricate,
    voiced_labiodental_affricate,
    voiced_labiodental_nasal,
    voiceless_labiodental_fricative,
    voiced_labiodental_fricative,
    voiced_labiodental_approximant,
    voiceless_alveolar_stop,
    voiced_alveolar_stop,
    voiceless_dental_stop,
    voiced_dental_stop,
    voiceless_dental_fricative,
    voiced_dental_fricative,
    voiced_alveolar_nasal,
    voiceless_alveolar_affricate,
    voiced_alveolar_affricate,
    voiceless_alveolar_fricative,
    voiced_alveolar_fricative,
    voiceless_alveolar_lat_affricate,
    voiced_alveolar_lat_affricate,
    voiceless_alveolar_lat_fric,
    voiced_alveolar_lat_fric,
    voiced_alveolar_approx,
    voiced_alveolar_trill,
    voiced_alveolar_tap,
    voiced_alveolar_lateral,
    dark_l,
    voiceless_pal_alv_affricate,
    voiced_pal_alv_affricate,
    voiceless_pal_alv_fricative,
    voiced_pal_alv_fricative,
    voiceless_velar_stop,
    voiced_velar_stop,
    voiced_velar_nasal,
    voiceless_uvular_stop,
    voiced_uvular_stop,
    voiced_uvular_nasal,
    glottal_stop,
    voiceless_glottal_fricative,
    voiceless_velar_fricative,
    voiced_velar_fricative,
    syllable_break,
    primary_stress,
    secondary_stress,
    long,
    half_long,
    top_diacritic,
    high_diacritic,
    mid_diacritic,
    low_diacritic,
    bottom_diacritic
]

let phones_by_name: { [key: string]: ipa_symbol } = {}
let phones_by_ipa_sym: { [key: string]: ipa_symbol } = {}
let phones_by_branner: { [key: string]: ipa_symbol } = {}
let letters_by_feature_string: { [key: string]: ipa_letter } = {}

const num_phones = all_phones.length
for (let i = 0; i < num_phones; i++) {
    const phone = all_phones[i]
    phones_by_name[phone.name] = phone
    phones_by_ipa_sym[phone.ipa_sym] = phone
    phones_by_branner[phone.branner] = phone
    if (is_letter(phone)) {
        const fs = get_feature_string(phone.features)
        letters_by_feature_string[fs] = phone
    }
}

export function get(key: string): ipa_symbol | undefined {
    if (phones_by_name[key]) {
        return phones_by_name[key]
    }

    if (phones_by_branner[key]) {
        return phones_by_branner[key]
    }

    if (phones_by_ipa_sym[key]) {
        return phones_by_ipa_sym[key]
    }

    return undefined
}

export function get_by_feature_string(key: string): ipa_letter | undefined {
    if (letters_by_feature_string[key]) {
        return letters_by_feature_string[key]
    }

    return undefined
}